### ISSUE TITLE
sporadically no mqtt data

### ISSUE THREAD

**Issue by JoB1l** [z-master42/solarflow#30]
Hi, since yesterday afternoon around 3pm I have sporadically no longer had any MQTT data. Is anyone else affected?

The app is running normally

![Solar Input](https://github.com/z-master42/solarflow/assets/143347727/eb2c4fc1-1524-4ce5-91f2-b24e4e720d61)

![mqtt explorer](https://github.com/z-master42/solarflow/assets/143347727/f8b7b21c-2b90-4705-88f3-9f789c15919d)

**Comment by phenomeus** [comment]
same, today is empty. no connection with mqtt explorer

**Comment by H0d0rKF** [comment]
Same here. Last two Days und today. I´ve got some Questions. Are you at the European MQTT Servers from Zendure or at the US ones? Are you using Auto Discovery for the Entitys or manuall Entities?

**Comment by JoB1l** [comment]
> Same here. Last two Days und today. I´ve got some Questions. Are you at the European MQTT Servers from Zendure or at the US ones? Are you using Auto Discovery for the Entitys or manuall Entities?

I use the EU server. I didn't want to switch to global for testing purposes because otherwise my statistics in the app would be lost.

I created the entities manually

**Comment by z-master42** [comment]
You can switch to test. The statistics are not lost but remain on the respective server.

**Comment by JoB1l** [comment]
Has anyone tried to see if the problem also exists on the global servers?

**Comment by z-master42** [comment]
The curious thing is: As far as I "know", the development server to get data via MQTT is the same for EU and Global. EU and Global only play a role in terms of which production server the hub and the app talk to. 

When binding the devices, only the connection of the respective production with the development server takes place. So if there are problems with EU, it should be due to the connection between the servers.

So far I have not noticed any dropouts with Global.

**Comment by wagnerpizza** [comment]
Hi i tried to connect via MQTT Explorer. All steps befor were successfull instead of HA MQTT. Thats why I tried MQTT Explorer. And nothing happend, no topic. Any idea? But in same moment the app works properly.

![mqtt](https://github.com/user-attachments/assets/26159545-9a56-4de5-a29c-f9f648718302)
![mqtt2](https://github.com/user-attachments/assets/995f1b38-d58c-443a-bd16-50704b8ebf63)
![mqtt3](https://github.com/user-attachments/assets/7ef338cc-7443-48f6-995e-e6ed17ff891c)

**Comment by z-master42** [comment]
You have a European country in the app under Region and in the answer regarding the query of appKey and appSecret the mqtt-eu came up as mqttUrl...?

The statement that the app is working means that the hub was switched on at the time and power was flowing?

**Comment by z-master42** [comment]
> I subscribed topic with "xxxxxxxxx#" (attatched)

There must be a / between appKey and #.
